# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7s15ftgb196-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/cho/Desktop/SEA_AZPR/hw/project/vivado201802/vivado201802.cache/wt [current_project]
set_property parent.project_path C:/Users/cho/Desktop/SEA_AZPR/hw/project/vivado201802/vivado201802.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/cho/Desktop/SEA_AZPR/hw/project/vivado201802/vivado201802.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/top/include/nettype.h
  C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/top/include/stddef.h
  C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/top/include/global_config.h
  C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/cpu/include/cpu.h
  C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/bus/include/bus.h
  C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/io/rom/include/rom.h
  C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/io/gpio/include/gpio.h
  C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/io/timer/include/timer.h
  C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/io/uart/include/uart.h
  C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/cpu/include/isa.h
  C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/cpu/include/spm.h
}
set_property file_type "Verilog Header" [get_files C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/top/include/nettype.h]
set_property file_type "Verilog Header" [get_files C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/top/include/stddef.h]
set_property file_type "Verilog Header" [get_files C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/top/include/global_config.h]
set_property file_type "Verilog Header" [get_files C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/cpu/include/cpu.h]
set_property file_type "Verilog Header" [get_files C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/bus/include/bus.h]
set_property file_type "Verilog Header" [get_files C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/io/rom/include/rom.h]
set_property file_type "Verilog Header" [get_files C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/io/gpio/include/gpio.h]
set_property file_type "Verilog Header" [get_files C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/io/timer/include/timer.h]
set_property file_type "Verilog Header" [get_files C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/io/uart/include/uart.h]
set_property file_type "Verilog Header" [get_files C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/cpu/include/isa.h]
set_property file_type "Verilog Header" [get_files C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/cpu/include/spm.h]
read_mem C:/Users/cho/Desktop/SEA_AZPR/sw/Sample_Program_SEA/1.LED/test_binary.dat
read_verilog -library xil_defaultlib {
  C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/cpu/rtl/alu.v
  C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/bus/rtl/bus.v
  C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/bus/rtl/bus_addr_dec.v
  C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/bus/rtl/bus_arbiter.v
  C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/cpu/rtl/bus_if.v
  C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/bus/rtl/bus_master_mux.v
  C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/bus/rtl/bus_slave_mux.v
  C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/top/rtl/chip.v
  C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/top/rtl/clk_gen.v
  C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/cpu/rtl/cpu.v
  C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/cpu/rtl/ctrl.v
  C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/cpu/rtl/decoder.v
  C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/cpu/rtl/ex_reg.v
  C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/cpu/rtl/ex_stage.v
  C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/io/gpio/rtl/gpio.v
  C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/cpu/rtl/gpr.v
  C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/cpu/rtl/id_reg.v
  C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/cpu/rtl/id_stage.v
  C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/cpu/rtl/if_reg.v
  C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/cpu/rtl/if_stage.v
  C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/cpu/rtl/mem_ctrl.v
  C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/cpu/rtl/mem_reg.v
  C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/cpu/rtl/mem_stage.v
  C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/io/rom/rtl/rom.v
  C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/cpu/rtl/spm.v
  C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/io/timer/rtl/timer.v
  C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/top/lib/x_s3e_dcm.v
  C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/top/lib/x_s3e_dpram.v
  C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/top/lib/x_s3e_sprom.v
  C:/Users/cho/Desktop/SEA_AZPR/hw/rtl_sea/top/rtl/chip_top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/cho/Desktop/SEA_AZPR/hw/project/vivado201802/vivado201802.srcs/constrs_1/imports/constraint/system.xdc
set_property used_in_implementation false [get_files C:/Users/cho/Desktop/SEA_AZPR/hw/project/vivado201802/vivado201802.srcs/constrs_1/imports/constraint/system.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top chip_top -part xc7s15ftgb196-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef chip_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file chip_top_utilization_synth.rpt -pb chip_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
